# Generated by Django 3.2.7 on 2023-06-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='morning_state',
            field=models.TextField(blank=True, null=True, verbose_name='朝の症状'),
        ),
        migrations.AlterField(
            model_name='health',
            name='morning_temperature',
            field=models.TextField(blank=True, null=True, verbose_name='朝の体温'),
        ),
        migrations.AlterField(
            model_name='health',
            name='night_state',
            field=models.TextField(blank=True, null=True, verbose_name='夜の症状'),
        ),
        migrations.AlterField(
            model_name='health',
            name='night_temperature',
            field=models.TextField(blank=True, null=True, verbose_name='夜の体温'),
        ),
        migrations.AlterField(
            model_name='health',
            name='niti',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
    ]
